# Generated by Django 4.2.7 on 2023-11-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=100)),
                ('inv_num', models.CharField(max_length=10)),
                ('ser_num', models.CharField(max_length=10)),
                ('place_pass', models.CharField(max_length=20)),
                ('status_pass', models.CharField(max_length=50)),
            ],
        ),
    ]
