# Generated by Django 4.2.7 on 2023-11-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='inv_num',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='place_pass',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='ser_num',
            field=models.CharField(max_length=50),
        ),
    ]
